name: CI/CD Pipeline

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run server-side deployment script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Ensure deployment directory exists and clone/update repo into agent_post
            mkdir -p /home/${{ secrets.SERVER_USERNAME }}/web_server
            cd /home/${{ secrets.SERVER_USERNAME }}/web_server
            if [ -d agent_post ]; then
              cd agent_post
              git fetch --all
              git reset --hard origin/production
            else
              git clone https://github.com/${{ github.repository_owner }}/agent_post.git agent_post
              cd agent_post
            fi

            # Create docker network if missing
            docker network ls | grep "shared_network" || docker network create shared_network

            # Stop and remove existing container if present
            if docker ps -a --format '{{.Names}}' | grep -q '^agent_post$'; then
              docker stop agent_post || true
              docker rm -f agent_post || true
            fi

            # Build image from the repository's Dockerfile and run it
            docker build -t agent_post:latest .
            docker run -d --name agent_post --network shared_network --restart unless-stopped agent_post:latest

            echo "Cleaning up unused Docker resources..."
            docker container prune -f
            docker image prune -f
