name: Test

on:
  push:
    branches: [ main, develop, feature/*, hotfix/* ] # Add other branches as needed
  pull_request:
    branches: [ main, develop ] # Add other branches as needed


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Or your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: .pytest_cache  #If you have reports you may add them