name: Test

on:
  push:
    branches: [ main, develop, feature/*, hotfix/* ] # Add other branches as needed
  pull_request:
    branches: [ main, develop ] # Add other branches as needed


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Or your Python version

      - name: Create virtual environment
        run: python3 -m venv .venv

      - name: Activate virtual environment
        run: source .venv/bin/activate

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: .pytest_cache  #If you have reports you may add them